-- Add migration script here
BEGIN;
ALTER TABLE news_info DROP CONSTRAINT uniq_news_info;
ALTER TABLE news_info ADD CONSTRAINT uniq_news_info UNIQUE (news_from, news_date);
COMMIT;

update news_info set name='参考消息' where news_from='cankaoxiaoxi';
update news_info set name='法布财经' where news_from='fastbull-express';
update news_info set name='虫部落' where news_from='chongbuluo-hot';
update news_info set name='虫部落' where news_from='chongbuluo-latest';
update news_info set name='财联社' where news_from='cls';
update news_info set name='雪球' where news_from='xueqiu-hotstock';
update news_info set name='虎扑' where news_from='hupu';
update news_info set name='Github' where news_from='github';
update news_info set name='财联社' where news_from='cls-depth';
update news_info set name='少数派' where news_from='sspai';
update news_info set name='IT之家' where news_from='ithome';
update news_info set name='Github' where news_from='github-trending-today';
update news_info set name='华尔街见闻' where news_from='wallstreetcn-quick';
update news_info set name='稀土掘金' where news_from='juejin';
update news_info set name='华尔街见闻' where news_from='wallstreetcn-news';
update news_info set name='凤凰网' where news_from='ifeng';
update news_info set name='百度热搜' where news_from='baidu';
update news_info set name='金十数据' where news_from='jin10';
update news_info set name='格隆汇' where news_from='gelonghui';
update news_info set name='Product Hunt' where news_from='producthunt';
update news_info set name='财联社' where news_from='cls-telegraph';
update news_info set name='MKTNews' where news_from='mktnews';
update news_info set name='雪球' where news_from='xueqiu';
update news_info set name='今日头条' where news_from='toutiao';
update news_info set name='靠谱新闻' where news_from='kaopu';
update news_info set name='财联社' where news_from='cls-hot';
update news_info set name='Freebuf' where news_from='freebuf';
update news_info set name='Hacker News' where news_from='hackernews';
update news_info set name='法布财经' where news_from='fastbull';
update news_info set name='远景论坛' where news_from='pcbeta-windows11';
update news_info set name='牛客' where news_from='nowcoder';
update news_info set name='微博' where news_from='weibo';
update news_info set name='联合早报' where news_from='zaobao';
update news_info set name='腾讯新闻' where news_from='tencent-hot';
update news_info set name='Steam' where news_from='steam';
update news_info set name='知乎' where news_from='zhihu';
update news_info set name='华尔街见闻' where news_from='wallstreetcn';
update news_info set name='豆瓣' where news_from='douban';
update news_info set name='法布财经' where news_from='fastbull-news';
update news_info set name='百度贴吧' where news_from='tieba';
update news_info set name='澎湃新闻' where news_from='thepaper';
update news_info set name='Solidot' where news_from='solidot';
update news_info set name='酷安' where news_from='coolapk';
update news_info set name='MKTNews' where news_from='mktnews-flash';
update news_info set name='抖音' where news_from='douyin';
update news_info set name='华尔街见闻' where news_from='wallstreetcn-hot';